name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: "9477386"

    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses
        yes | sdkmanager --install "platforms;android-34"
        yes | sdkmanager --install "build-tools;34.0.0"

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      env:
        ANDROID_HOME: ${{ runner.workspace }}/android-sdk
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        ./gradlew assembleDebug --stacktrace

    - name: List APK directory
      run: ls -l app/build/outputs/apk/debug/

    - name: List build reports directory
      run: ls -l app/build/reports/

    - name: Upload APK
      if: success() && (exists('app/build/outputs/apk/debug/app-debug.apk'))
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload build reports
      if: always() && (exists('app/build/reports/'))
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: app/build/reports/
