name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: "9477386"

    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses
        yes | sdkmanager --install "platforms;android-34"
        yes | sdkmanager --install "build-tools;34.0.0"

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      env:
        ANDROID_HOME: ${{ runner.workspace }}/android-sdk
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        ./gradlew assembleDebug --stacktrace

    - name: List APK directory
      run: ls -l app/build/outputs/apk/debug/

    - name: List build reports directory
      run: ls -l app/build/reports/

    - name: Upload APK
      if: success() && (exists('app/build/outputs/apk/debug/app-debug.apk'))
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.zip
        path: app/build/outputs/apk/debug/app-debug.apk

    # Note: The uploaded APK artifact can be downloaded from the GitHub Actions run summary page under "Artifacts".

    # Release build with signing
    - name: Setup signing key
      if: github.event_name == 'push'
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore
      shell: bash

    - name: Build release APK
      env:
        ANDROID_HOME: ${{ runner.workspace }}/android-sdk
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        ./gradlew assembleRelease -Pandroid.injected.signing.store.file=release.keystore \
          -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
          -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
          -Pandroid.injected.signing.key.password=$KEY_PASSWORD --stacktrace

    - name: List release APK directory
      run: ls -l app/build/outputs/apk/release/

    - name: Check if release APK exists
      run: |
        if [ -f app/build/outputs/apk/release/app-release.apk ]; then
          echo "Release APK exists."
        else
          echo "Release APK does NOT exist."
          exit 1
        fi

    - name: Upload release APK
      if: success() && (exists('app/build/outputs/apk/release/app-release.apk'))
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload build reports
      if: always() && (exists('app/build/reports/'))
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: app/build/reports/
