name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup build environment
      run: |
        echo "org.gradle.daemon=false" >> gradle.properties
        echo "org.gradle.jvmargs=-Xmx2g" >> gradle.properties
        echo "android.enableJetifier=false" >> gradle.properties

    - name: Build app module
      run: ./gradlew :app:assembleDebug --scan

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk
